#!/bin/bash
rm -rf __pycache__
rm -rf rule_builder/__pycache__
rm -rf WebHostLib/api/__pycache__
rm -rf WebHostLib/cli/__pycache__
rm -rf WebHostLib/__pycache__
rm -rf worlds/adventure/__pycache__
rm -rf worlds/ahit/__pycache__
rm -rf worlds/alttp/__pycache__
rm -rf worlds/apquest/__pycache__
rm -rf worlds/apsudoku/__pycache__
rm -rf worlds/aquaria/__pycache__
rm -rf worlds/_bizhawk/__pycache__
rm -rf worlds/blasphemous/__pycache__
rm -rf worlds/bomb_rush_cyberfunk/__pycache__
rm -rf worlds/bumpstik/__pycache__
rm -rf worlds/cccharles/__pycache__
rm -rf worlds/celeste64/Names/__pycache__
rm -rf worlds/celeste64/__pycache__
rm -rf worlds/celeste_open_world/data/__pycache__
rm -rf worlds/celeste_open_world/Names/__pycache__
rm -rf worlds/celeste_open_world/__pycache__
rm -rf worlds/checksfinder/__pycache__
rm -rf worlds/civ_6/data/__pycache__
rm -rf worlds/civ_6/__pycache__
rm -rf worlds/cv64/data/__pycache__
rm -rf worlds/cv64/__pycache__
rm -rf worlds/cvcotm/data/__pycache__
rm -rf worlds/cvcotm/__pycache__
rm -rf worlds/dark_souls_3/__pycache__
rm -rf worlds/dkc3/Names/__pycache__
rm -rf worlds/dkc3/__pycache__
rm -rf worlds/dlcquest/data/__pycache__
rm -rf worlds/dlcquest/__pycache__
rm -rf worlds/doom_1993/__pycache__
rm -rf worlds/doom_ii/__pycache__
rm -rf worlds/earthbound/game_data/__pycache__
rm -rf worlds/earthbound/gifting/__pycache__
rm -rf worlds/earthbound/modules/enemizer/__pycache__
rm -rf worlds/earthbound/modules/__pycache__
rm -rf worlds/earthbound/__pycache__
rm -rf worlds/factorio/__pycache__
rm -rf worlds/faxanadu/__pycache__
rm -rf worlds/ff1/__pycache__
rm -rf worlds/ffmq/data/__pycache__
rm -rf worlds/ffmq/__pycache__
rm -rf worlds/generic/__pycache__
rm -rf worlds/heretic/__pycache__
rm -rf worlds/hk/__pycache__
rm -rf worlds/hylics2/__pycache__
rm -rf worlds/inscryption/__pycache__
rm -rf worlds/jakanddaxter/locs/__pycache__
rm -rf worlds/jakanddaxter/__pycache__
rm -rf worlds/jakanddaxter/regs/__pycache__
rm -rf worlds/kdl3/names/__pycache__
rm -rf worlds/kdl3/__pycache__
rm -rf worlds/kh1/__pycache__
rm -rf worlds/kh2/__pycache__
rm -rf worlds/ladx/LADXR/locations/__pycache__
rm -rf worlds/ladx/LADXR/logic/__pycache__
rm -rf worlds/ladx/LADXR/mapgen/locations/__pycache__
rm -rf worlds/ladx/LADXR/mapgen/__pycache__
rm -rf worlds/ladx/LADXR/mapgen/roomtype/__pycache__
rm -rf worlds/ladx/LADXR/patches/__pycache__
rm -rf worlds/ladx/LADXR/__pycache__
rm -rf worlds/ladx/__pycache__
rm -rf worlds/landstalker/data/__pycache__
rm -rf worlds/landstalker/__pycache__
rm -rf worlds/lingo/__pycache__
rm -rf worlds/lufia2ac/basepatch/__pycache__
rm -rf worlds/lufia2ac/__pycache__
rm -rf worlds/marioland2/__pycache__
rm -rf worlds/meritous/__pycache__
rm -rf worlds/messenger/__pycache__
rm -rf worlds/mlss/Names/__pycache__
rm -rf worlds/mlss/__pycache__
rm -rf worlds/mm2/__pycache__
rm -rf worlds/mm3/__pycache__
rm -rf worlds/mmbn3/Names/__pycache__
rm -rf worlds/mmbn3/__pycache__
rm -rf worlds/musedash/__pycache__
rm -rf worlds/noita/__pycache__
rm -rf worlds/oot/__pycache__
rm -rf worlds/osrs/LogicCSV/__pycache__
rm -rf worlds/osrs/__pycache__
rm -rf worlds/overcooked2/__pycache__
rm -rf worlds/paint/__pycache__
rm -rf worlds/pokemon_emerald/__pycache__
rm -rf worlds/pokemon_rb/__pycache__
rm -rf worlds/__pycache__
rm -rf worlds/raft/__pycache__
rm -rf worlds/ror2/__pycache__
rm -rf worlds/sa2b/Names/__pycache__
rm -rf worlds/sa2b/__pycache__
rm -rf worlds/satisfactory/__pycache__
rm -rf worlds/saving_princess/__pycache__
rm -rf worlds/sc2/item/__pycache__
rm -rf worlds/sc2/mission_order/__pycache__
rm -rf worlds/sc2/__pycache__
rm -rf worlds/shapez/common/__pycache__
rm -rf worlds/shapez/data/__pycache__
rm -rf worlds/shapez/__pycache__
rm -rf worlds/shivers/__pycache__
rm -rf worlds/shorthike/__pycache__
rm -rf worlds/sm/__pycache__
rm -rf worlds/sm/variaRandomizer/graph/__pycache__
rm -rf worlds/sm/variaRandomizer/graph/vanilla/__pycache__
rm -rf worlds/sm/variaRandomizer/logic/__pycache__
rm -rf worlds/sm/variaRandomizer/patches/common/__pycache__
rm -rf worlds/sm/variaRandomizer/patches/__pycache__
rm -rf worlds/sm/variaRandomizer/__pycache__
rm -rf worlds/sm/variaRandomizer/rando/__pycache__
rm -rf worlds/sm/variaRandomizer/rom/__pycache__
rm -rf worlds/sm/variaRandomizer/utils/__pycache__
rm -rf worlds/sm64ex/__pycache__
rm -rf worlds/smw/Names/__pycache__
rm -rf worlds/smw/__pycache__
rm -rf worlds/smz3/__pycache__
rm -rf worlds/smz3/TotalSMZ3/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/SuperMetroid/Brinstar/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/SuperMetroid/Crateria/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/SuperMetroid/Maridia/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/SuperMetroid/NorfairLower/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/SuperMetroid/NorfairUpper/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/SuperMetroid/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/Zelda/DarkWorld/DeathMountain/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/Zelda/DarkWorld/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/Zelda/LightWorld/DeathMountain/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/Zelda/LightWorld/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Regions/Zelda/__pycache__
rm -rf worlds/smz3/TotalSMZ3/Text/__pycache__
rm -rf worlds/soe/__pycache__
rm -rf worlds/stardew_valley/bundles/__pycache__
rm -rf worlds/stardew_valley/content/feature/__pycache__
rm -rf worlds/stardew_valley/content/mods/__pycache__
rm -rf worlds/stardew_valley/content/__pycache__
rm -rf worlds/stardew_valley/content/vanilla/__pycache__
rm -rf worlds/stardew_valley/data/bundles_data/meme_bundles_data/__pycache__
rm -rf worlds/stardew_valley/data/bundles_data/__pycache__
rm -rf worlds/stardew_valley/data/__pycache__
rm -rf worlds/stardew_valley/items/__pycache__
rm -rf worlds/stardew_valley/logic/__pycache__
rm -rf worlds/stardew_valley/mods/logic/__pycache__
rm -rf worlds/stardew_valley/mods/__pycache__
rm -rf worlds/stardew_valley/options/__pycache__
rm -rf worlds/stardew_valley/__pycache__
rm -rf worlds/stardew_valley/regions/__pycache__
rm -rf worlds/stardew_valley/stardew_rule/__pycache__
rm -rf worlds/stardew_valley/strings/ap_names/mods/__pycache__
rm -rf worlds/stardew_valley/strings/ap_names/__pycache__
rm -rf worlds/stardew_valley/strings/__pycache__
rm -rf worlds/subnautica/__pycache__
rm -rf worlds/terraria/__pycache__
rm -rf worlds/timespinner/__pycache__
rm -rf worlds/tloz/__pycache__
rm -rf worlds/tunic/__pycache__
rm -rf worlds/tww/__pycache__
rm -rf worlds/tww/randomizers/__pycache__
rm -rf worlds/undertale/__pycache__
rm -rf worlds/v6/__pycache__
rm -rf worlds/wargroove/__pycache__
rm -rf worlds/witness/data/__pycache__
rm -rf worlds/witness/data/settings/__pycache__
rm -rf worlds/witness/__pycache__
rm -rf worlds/yachtdice/__pycache__
rm -rf worlds/yoshisisland/__pycache__
rm -rf worlds/yugioh06/__pycache__
rm -rf worlds/zillion/__pycache__
